import pygame

def set_key_bindings(keyboard_mappings):
    keyboard_mappings[pygame.K_a] = "a"
    keyboard_mappings[pygame.K_b] = "b"
    keyboard_mappings[pygame.K_c] = "c"
    keyboard_mappings[pygame.K_d] = "d"
    keyboard_mappings[pygame.K_e] = "e"
    keyboard_mappings[pygame.K_f] = "f"
    keyboard_mappings[pygame.K_g] = "g"
    keyboard_mappings[pygame.K_h] = "h"
    keyboard_mappings[pygame.K_i] = "i"
    keyboard_mappings[pygame.K_j] = "j"
    keyboard_mappings[pygame.K_k] = "k"
    keyboard_mappings[pygame.K_l] = "l"
    keyboard_mappings[pygame.K_m] = "m"
    keyboard_mappings[pygame.K_n] = "n"
    keyboard_mappings[pygame.K_o] = "o"
    keyboard_mappings[pygame.K_p] = "p"
    keyboard_mappings[pygame.K_q] = "q"
    keyboard_mappings[pygame.K_r] = "r"
    keyboard_mappings[pygame.K_s] = "s"
    keyboard_mappings[pygame.K_t] = "t"
    keyboard_mappings[pygame.K_u] = "u"
    keyboard_mappings[pygame.K_v] = "v"
    keyboard_mappings[pygame.K_w] = "w"
    keyboard_mappings[pygame.K_x] = "x"
    keyboard_mappings[pygame.K_y] = "y"
    keyboard_mappings[pygame.K_z] = "z"

    keyboard_mappings[pygame.K_UP] = "up"
    keyboard_mappings[pygame.K_LEFT] = "left"
    keyboard_mappings[pygame.K_DOWN] = "down"
    keyboard_mappings[pygame.K_RIGHT] = "right"

    keyboard_mappings[pygame.K_ESCAPE] = "esc"
    keyboard_mappings[pygame.K_TAB] = "tab"

    keyboard_mappings[pygame.K_1] = "1"
    keyboard_mappings[pygame.K_2] = "2"
    keyboard_mappings[pygame.K_3] = "3"
    keyboard_mappings[pygame.K_4] = "4"
    keyboard_mappings[pygame.K_5] = "5"
    keyboard_mappings[pygame.K_6] = "6"
    keyboard_mappings[pygame.K_7] = "7"
    keyboard_mappings[pygame.K_8] = "8"
    keyboard_mappings[pygame.K_9] = "9"
    keyboard_mappings[pygame.K_PERIOD] = "."
    keyboard_mappings[pygame.K_RETURN] = "return"
    keyboard_mappings[">"] = ">"
    keyboard_mappings["<"] = "<"

